name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: |
          npm install ESA-EarthCODE/open-science-catalog-validation#v1.0.0-rc.6
      - name: Validate
        run: |
          npx open-science-catalog-validation ./eo-missions ./products ./projects ./themes ./variables
